### ISSUE TITLE
Community Suggestions

### ISSUE THREAD

**Issue by Shadows-of-Fire** [makeoo/Gadomancy#14]
1. Black Hole Mirror
   - Teleporting Mirror (Alienis essentia as a cost)
2. Pylon of Eternal Clockwork
   - Speed up / Stop time 
3. Golem Core: Sentinel
   - Skeleton-like AI, Golems use bows, Semi-stationary, upgrade from GC: Guard, Non-Metal Golems ONLY
4. Golem Lord's Amulet
   - Empowers nearby Sentinel, Berserker, Guard, or Bodyguard golems.
5. Thaumic Manipulator (Adv Arcane Dropper)
   - Detects items in GUI free Tile Entities (Botania / Aura Cascade)
6. Golem Core: Berserker
   - Zombie-like AI, Golems lose base stats in order to equip Swords/Armor, Semi-stationary. Upgrade from GC: Guard. Metal Golems ONLY
7. The Order of Purification
   - Inverse of the Crimson Cult, they seek to halt the Eldritch advance into the overworld.
8. Golemic Expansion 
   - Incorporation of multiple Cores into a singular golem.
9. Essentia Forge
   *Using essentia, creations like never before reveal themselves to you.  The safety of the device is well, questionable...

**Comment by HellFirePvP** [comment]
Thx for creating this list - I hope you will keep it updated :P Of course we'll help^^

Makeo and i will discuss on the topics above and if we can announce something we'll edit the entry in the list.

**Comment by Shadows-of-Fire** [comment]
Updated names to fit a more Thaumic theme, added names where only a concept was given.

**Comment by gordontheniffler** [comment]
Wand cap Idea- right click red stone with wand to deliver a red stone signal

Wand cap of transport -  basically a thaumic portal gun.

**Comment by makeo** [comment]
"Golem Core: Templar"/"Golem Core: Bodyguard" will be in the next version

Focal Activator will not be implemented due to tc 5 already adding it.

**Comment by Shadows-of-Fire** [comment]
Does the ethereal familiar count as the incorporation of the aforementioned "Golem Lord's Amulet"? I want to make sure as I haven't had the chance to update my MC environment (pushing out server updates is a hassle) to check, and I don't want to remove anything from this list that isn't implemented

**Comment by makeo** [comment]
yes this is our version of the Golem Lord's Amulet. But we will add more functionality to it in future updates :)

**Comment by 63502** [comment]
I like the golem lord's amulet, but with the ethereal familiar now implemented, I don't think the golem riding player idea is viable anymore. The amulet could be an entirely support based bauble that gives golems potion effects when  close to the player at the cost of vis from a wand/staff, or perhaps it could speed up the recharge of golem runic shields in an area around the player at the cost of vis. Both ideas seem reasonable enough, especially with the new Golem Core: Bodyguard.

**Comment by Shahelion** [comment]
Instead of the Cobalt Cult (too similar to Crimson Cult, I feel) how about maybe the Sapphire Sect? Cobalt Clan? Opal Order? Something to make it stand apart a little more.

**Comment by Shadows-of-Fire** [comment]
Might change the name in the list when im not on mobile

**Comment by SpiderOverlord** [comment]
blade of darkness: a blade forged from a void metal sword, an element of darkness and 2 primordial pearls plus some voidmetal, basically this weapon can blind and wither enemies while dealing about 10+ melee damage. has self repairing hence the voidmetal
