### ISSUE TITLE
Thaumonomicon Pages (by Redcreeper63502)

### ISSUE THREAD

**Issue by 63502** [makeoo/Gadomancy#20]
ENTRIES..................................THERE ARE ENTRIES HERE.

I'm done with my midterms for now, so I can finally write thaumonomicon pages!  XD
I have no idea how to format the text properly, so I do apologize in advance.

Sticky Jar:
Warded jars are any thaumaturge's bread and butter; however, they can be a bit difficult to arrange  when large tangles of essentia tubes get involved. You decided to alleviate this minor difficulty by applying some adhesive to the bottom of the jar. Any jar that has had its base coated will stick to any surface it is placed on, even facing sideways or upside down. Breaking the jar does not remove the adhesive, allowing sticky jars to be reused. Also, many other types of essentia containing jars other than basic warded jars can accept this alteration.

Mirrored Jar:
The essentia mirror is excellent for moving essentia around for infusions, but you have the uncanny feeling that it has some untapped potential. 
Two essentia mirrors, when linked, effectively allow essentia to move between two points in space. By placing an essentia mirror inside of a specially altered warded jar, the space inside of one jar can be effectively linked to another. 
In order to link two jars, simply place one in the world and right click it with another mirrored jar. If a network already exists, then the jar will be added to the current network. Unlike essentia mirrors, mirrored jar networks can have more than two jars.
The space inside of a network is shared and balanced between the jars it contains. To put it simply, a two jar network will hold two jars of essentia, a three jar network will hold three, etc. Also, when one mirrored jar is filled, it will attempt to evenly distribute its contents between the other jars in its network.
Mirrored jars can accept the sticky upgrade.

Alright, there's my first two thaumonomicon entries; I hope you like them. :D
I should have the Arcane hopper and current golem stuff entries ready in the next few days.

Thanks
     63502

**Comment by BBoldt** [comment]
Wow, 19 minutes after I submitted this PR:
https://github.com/makeoo/Gadomancy/pull/19

**Comment by BBoldt** [comment]
We were probably writing the entries at the exact same time, hilariously.

Instead of doing two of them, I did them all though. :stuck_out_tongue_closed_eyes:

**Comment by makeo** [comment]
Thanks to both of you! i'll take a look at it in a few hours and merge both of your texts :)

**Comment by BBoldt** [comment]
You're going to have to pick your favorites. :P

**Comment by makeo** [comment]
Ahhh I will regret my decisions right? But at least i can blame HellFire for that :P

**Comment by HellFirePvP** [comment]
Why is it always me who gets blamed in the end -_-

**Comment by makeo** [comment]
Ok we will use your Mirrored Jar text @63502.
For the other texts we will use @BBoldt.
We'll mention both you in our special thanks section :) amazing work

**Comment by 63502** [comment]
:D
