### ISSUE TITLE
No In game indication on how to use the Ethereal Familiar

### ISSUE THREAD

**Issue by Zebia** [makeoo/Gadomancy#24]
Neither the Items entry nor it's icon indicate that your supposed to wear the thing and my natural assumption from similar items (golems) was that you placed it on the ground , I was about to file a report saying It wasn't working when I ran into how to use it in the entry report. something to clarify how it's used would be nice (i.e. Changing the Inventory icon to a necklace, using a mundane amulet as part of it's recipe, Putting "Goes in the amulet slot" in a line below the items name in the hover text, correcting the Thauminomicon entry to include that it's a Bauble)

**Comment by makeo** [comment]
Yeah your right its not obvious that it is an amulet we will add the line "Goes in your amulet slot" and maybe change the recipe. A Icon would be nice but HellFire and me are not really capable of creating textures.
Thanks for informing us

**Comment by 63502** [comment]
I am going to be revising some of the thaumonomicon entries, so ill make sure to include that.
Revisions will be posted in a different issue

**Comment by makeo** [comment]
@63502 Thanks :)

**Comment by HellFirePvP** [comment]
@63502 Just to mention, we won't go and say everything there is about an item/block - for example we won't say the range, attack damage, attack speed of the Ethereal Familiar, or the exact results for the Node Manipulator and its percentage chances. So there will never be something like a clear, straight set of information in the thaumonomicon.

I won't say that not mentioning that the Ethereal Familiar should be placed in the amulet slot was intentional, but i think you got a raw idea of what i want to say. So respect that to some degree.

**Comment by Zebia** [comment]
@HellFirePvP That's understandable(1), Its just that; as is; it's a notable Usability Issue(2), thus the bug report. 

(1) and desirable as it preserves a feeling your going for
(2) If I can't figure it out without looking it up on github; and I'm relatively savvy when it comes to mods; whats my hypothetical 13 year old server player(or YouTube LP'er :laughing:) going to do?

**Comment by HellFirePvP** [comment]
All those 13YO youtubers -_-"

Well, already said, we're adding some information about that next version - Next version will come somewhat soon i guess..

**Comment by Zebia** [comment]
Hey, they have it tough dude! The Server Player at least has an (ostensibly) knowledgable Admin to fall back on, meanwhile the LP'er is left to the whims of youtube commenters, this on top of the (very prevalent) 'goldfish' inducement caused by the act of recording itself!

Looking forward to it!

**Comment by 63502** [comment]
@HellFirePvP Of course I won't say everything about the items; I'm fixing some grammar type stuff and adding some necessary details. I am doing my best to refrain from changing the concepts and lore already in the entries, but if I do, I'll be sure to run it by you and @makeoo . ;)

**Comment by HellFirePvP** [comment]
Also note that we'll change the Ethereal Familiar Infusion recipe - there will be an runic shielding amulet needed in the center, and 2 nitor around it instead of 2 of the mixed crystal clusters - If you want you may add the "turning defensive into offensive" thingy into the lore ;) _(Just to clarify stuff)_

**Comment by Zebia** [comment]
Will you be adding compatibility with the 'Runic Shielding Augmentation' infusion to it? (as its VTC slot rival the 'Amulet of Vis Storage' already possesses)

**Comment by makeo** [comment]
My opinion is that this would be quite op and I like that you have to give up your amulet slot. And a fully upgraded Familar is really strong so.... Maybe, maybe not

**Comment by Shadows-of-Fire** [comment]
Maybe add some defensive functions or even a mini amulet of vis storage agment after the max upgrade, the amulet slot is already coveted enough in base thaum, not to mention with botania or basically anything that utilizes baubles. I get the concept of meaningful choices, but full offence is usually weaker compared to defensive options as far as baubles go.

**Comment by HellFirePvP** [comment]
@Zebia I have no intentions to do so. I'd like the Ethereal Familiar to be an offensive choice, not a mixture.

@Shadows-of-Fire I'm well aware of the competition going on about the baubles slots, but as far as it goes, i can only see utility or defensive options and no real equivalent offensive choices.

As far as this goes, we will try to add offensive choices for the baubles slots as well as balancing the damage the items do/give you to make it somewhat equivalent to defensive items. Of course in the end it should be your choice if you want to fight a boss ~10 seconds longer, but have more health/armor/whatever, than killing the boss faster, but with the potential risk of dying. We will try to find a balance to that and we try to make those items scaling with your progress in thaumcraft & gadomancy.

**Comment by 63502** [comment]
@HellFirePvP Got it :)
