### ISSUE TITLE
Thaumonomicon Entry Revisions (by 63502)

### ISSUE THREAD

**Issue by 63502** [makeoo/Gadomancy#26]
I have the revisions ready! :D 
I pretty much just made an altered copy of the en_US.lang file. Most of the fixes are little grammatical and wording changes.

In terms of major rewrites, I redid the entry for the ethereal familiar. I tried to take all of the possibilities of changes mentioned in #25  into account. The revised entry should be ok for now, and if the familiar is changed in the near future, it should be easy enough to add on to.

The only other rewrite I did was for the node manipulator. I feel that the previous entry didn't read smoothly and wasn't very clear on some of the general lore as well as the the general workings of the device. I tried to refrain from adding and changing to much, but if you have any suggestions or concerns, please let me know.

File is on Pastebin. I hope you like it!
     63502

Pastebin Link: http://pastebin.com/8EVBQk8T
# NoMoreWallsOfTextInTheComments

**Comment by HellFirePvP** [comment]
Oh wow this will be so exciting to compare and see where are the changes -_-" :grin:

I'll read through it and merge it with the current language file. Of course thank you for your continous help ;) Much appreciated! :D

#TheWallsMovedToPastebin #ThereAreAlwaysWalls

**Comment by HellFirePvP** [comment]
I've just read through all the entries again and it really sounds much smoother

The recipe for the ethereal familiar also changed to the one i described before - changed the central item to amulet of runic shielding & 2 mixed crystal clusters to 2 nitor.

These changes will obviously come with the next update - we can't really tell when that will be but we try our best to release something new as soon as possible ;)

Again thanks for your massive help^^

~Closing issue~

**Comment by 63502** [comment]
@HellFirePvP  I'm glad to help! :D 

#TextWallsForever LOL

**Comment by Dayyer1** [comment]
Brilliant with the changing of the ethereal familiar's entries, it really opens up the possibilities.
Not that anything will be added. I don't have anything to do with the mod, I'm just saying nuce job. :D

**Comment by 63502** [comment]
:D
