### ISSUE TITLE
Definite New Features 

### ISSUE THREAD

**Issue by 63502** [makeoo/Gadomancy#28]
I would assume that the next update will primarily be re-balancing and bug fixes, but as of now, are there any ideas or suggestions that you guys will definitely implement in the near future?

This is mostly just me being curious, but I would definitely like to know about any planned features and concepts  so I can start roughing out thaumonomicon entries.

**Comment by HellFirePvP** [comment]
well there will be 2 new features we're working on. (1 i'm primarily working on, 1 makeo's working on :P) We'll tell you soon enough via pm how these new features will work, how users can access them, what's the idea behind it and how they're crafted and whatsoever.

However we don't want to talk about what we're planning in public, please respect that~

**Comment by 63502** [comment]
Of course, I understand the whole publicity thing.
I'll wait for the pm.

Thanks! :)
