### ISSUE TITLE
Gadomancy 1.0.5 Revisions

### ISSUE THREAD

**Issue by 63502** [makeoo/Gadomancy#32]
Firstly, excellent job with this update. I played around with the new content for several hours late last night, and all new content seems to be working beautifully so far.
# 

In terms of revisions, I made a few wording and grammar fixes here and there, mostly just replacing one or two words.

I changed the enervation emitter entry to reflect the full extent of its functions, and the ethereal familiar entry to fit the modified behavior.

Also, while I was testing the ethereal familiar today, I noticed that it still auto attacks zombies, skeletons, witches, and creepers. Is it supposed to ignore neutral mobs like spiders and endermen until provoked? Is that a bug?
# 

Anyway, modified en_US.lang is on pastebin, hope you like it!
     63502

Pastebin Link: http://pastebin.com/LrLwSVHp

**Comment by HellFirePvP** [comment]
Well, i/we changed the way the Ethereal Familiar attacks and it basically supports you attacking something - meaning if you attack a mob, it will attack the same mob too - and it does attack mobs that target you with their AI - sadly Spiders, Slimes and as you say Endermen do not "Target" the player the way mobs normally do.. so you'd have to attack them and then the familiar helps though.

But everything else is working the way it should.

**Comment by 63502** [comment]
Ah.... I see.

**Comment by makeo** [comment]
Added in 1.0.6 :)
