### ISSUE TITLE
Compatibility issue with Witching Gadgets

### ISSUE THREAD

**Issue by esidav** [makeoo/Gadomancy#34]
In case of installing gadomancy with Witching Gadgets, Primordial Gauntlet becomes less able to grab an aura node.
Please solve this issue if possible.

https://github.com/BluSunrize/WitchingGadgets/

**Comment by HellFirePvP** [comment]
It's an "issue" with WitchingGadgets, because of this statement: "tile.getClass().equals(TileNode.class)"

With Gadomancy installed, this is always "false" for the nodes you see in the world. I'll ask the developer of witching gadgets to improve his code so it works with our mod. Anyway we can't change it on our side unfortunately. There is no way our side, i'm sorry.

As said above, i'll create an issue on WitchingGadgets' github and i'll comment the link to it here.

#Edit: link added itself.

**Comment by esidav** [comment]
Thank you for detailed explanation and adding new issue to WG's github :)
I understood the point.
I'll wait for response from BluSunrize.

**Comment by makeo** [comment]
Soo BluSunrize said that he won't fix it anytime soon...
But what we can do is add a config option to disable our node feature so you can atleast use all the other features of our mod.
So we will probably include that config option next update

**Comment by esidav** [comment]
Okay, config option is reasonable solution.
Thanks :)
So, you mean I won't be able to use node manipulation and eldlitch rituals by config off?

**Comment by makeo** [comment]
No :) only our custom node type will be disabled. Our mod adds a custom node type that you can obtain using the node manipulator and with the config option off you can't obtain this node type but you can still use the node manipulator and the eldritch ritual :)

**Comment by esidav** [comment]
Good, thanks :)
I'll wait next update.

**Comment by makeo** [comment]
Added the config option to disable our custom node types in 1.0.6
Maybe there is a better fix someday...

**Comment by esidav** [comment]
I checked config option.
Nodes created after cfg_off can be grabbed by gauntlet, and then turned cfg_true. Thanks!
So, thaumonomicon research entries about growing node disappeard.
How can I reopen researches? Just operate node manipulation?

**Comment by makeo** [comment]
If you disable the config option the growing node is gone like this part of our mod never existed. Thats why the researches disapear.. I'm really sorry but thats the only fix we can provide at the moment

**Comment by esidav** [comment]
Thank you for replying.

I understood why researches disappered.
It' not my point.
My point is concerned with how to re-enable custom nodetypes or research entries by changing config from false to true.

In my understanding, config option affects just only the nodes that are created/generated AFTER changing config.
Because existed growing node in my world hasn't gone after changing config to false.
And I returned config to true, growing node hasn't gone, of course.
But research entries haven't returned yet.

**Comment by makeo** [comment]
Chaning the config will affect all nodes and the growing type will convert to normal nodes. This might not happen if you did not load the chunk with the node and you have to change this config on client and server to take effect.
I think you need to create a new growing node to get the research back

**Comment by esidav** [comment]
Hmm... but my growing node is in front of me.

Anyway, I will try to create new growing node.
Thanks!

**Comment by Shadows-of-Fire** [comment]
Thaumcraft research is stored in a file called _playername_.thaum in the playerdata folder of your world save. If you back that file up when you swap off the nodes, then restore it after, it will preserve all research.

**Comment by ghost** [comment]
sorry for the necro. 

i fixed this problem on my  custom Witching Gadgets build really easy

simply used instanceof TileNode instead of .equals(TileNode) which always fails in Gadomancy because it  converts all nodes into TileNodeExtended which extends TileNode .

But note that even with Gadomancy Pure Nodes and Totem  Nodes can still be grabbed by the glove

**Comment by Arsterid** [comment]
> sorry for the necro.
> 
> i fixed this problem on my custom Witching Gadgets build really easy
> 
> simply used instanceof TileNode instead of .equals(TileNode) which always fails in Gadomancy because it converts all nodes into TileNodeExtended which extends TileNode .
> 
> But note that even with Gadomancy Pure Nodes and Totem Nodes can still be grabbed by the glove

How can I do it?
