### ISSUE TITLE
Console spam with Veinminer/NEI [1.0.5]

### ISSUE THREAD

**Issue by dirtyfargo** [makeoo/Gadomancy#37]
Mod Version: 1.0.5
Forge Version: 10.13.4.1566
VeinMiner Version: 0.30.2
NEI Version: 1.0.5.118
Description: Client console spamming this:

[10:05:37] [NEI Item Filtering/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@1). This won't work very well.
[10:05:37] [NEI Item Filtering/ERROR] [VeinMiner/]: NPE getting unique identifier for class makeo.gadomancy.common.items.ItemFakeGolemPlacer
[10:05:37] [NEI Item Filtering/ERROR] [VeinMiner/]: Contact the mod author responsible.

I'm not sure if it's actually causing any issues game-play wise, but thought I'd mention it anyways just in case :)

**Comment by HellFirePvP** [comment]
We're adding an NEI Integration in the future to blacklist items we don't want to be listed in there. As far as we experienced it with NEI there are no issues game-play wise, except that you can see some invalid items in NEI. We're fixxing that in the somewhat near future, but as it causes no real issue, we're prioritizing other things.

Thanks for the report tho

**Comment by dirtyfargo** [comment]
No problem, thanks for the quick reply =)

**Comment by makeo** [comment]
I just added the NEI integration. So this "issue" will be fixed next update

**Comment by Revemohl** [comment]
Doesn't seem to be fixed, as I'm still getting the spam on Gadomancy 1.0.7.2. 
Although I can't be sure if VeinMiner has fixed this on their side, because I'm using an older version (0.31.6) since 0.34.1 gives me problems with BuildCraft.
