### ISSUE TITLE
Arcane Dropper crash when using Applied Energistics storage bus

### ISSUE THREAD

**Issue by Thedrummonger** [makeoo/Gadomancy#38]
When you place an Applied Energistics storage bus on an Arcane Dropper and attempt to retrieve an item using an ME Terminal the game will crash.

Crash log
http://pastebin.com/8zEsJ6nQ

**Comment by HellFirePvP** [comment]
Thanks, we'll look into it and fix it for the next version ;)

**Comment by makeo** [comment]
Fixed in 1.0.6
