### ISSUE TITLE
Familiars will not float around the heads of players properly

### ISSUE THREAD

**Issue by Sunconure11** [makeoo/Gadomancy#40]
For some reason, familiars will follow other players, as opposed to the one that is owning it, on a server.

**Comment by HellFirePvP** [comment]
Can you please provide more information about the issue? Like, when does it happen? Is there some sort of pattern to the issue or how can we recreate it?

Also, how does that look like? Does your own familiar, when you equip it, spawn on another player? Does it just fly away from you to some other player?

**Comment by Sunconure11** [comment]
Basically, when I am near another player with a familiar, it spawns on me.

**Comment by HellFirePvP** [comment]
We'll look into it and fix it for the next update.

**Comment by makeo** [comment]
Fixed in 1.0.6
