### ISSUE TITLE
Golem Break core showing up as Empty

### ISSUE THREAD

**Issue by malhavok13** [makeoo/Gadomancy#41]
Using Baubles 1.0.1.10 and Thaumcraft 4.2.3.5 with Gadomancy 1.0.5, no other mods.
Also have Forge 1614
When I click on the golem his commands are for the empty core. I created all the basic golems types plus the new silverwood version and all are the same, Empty cores. The picture in the command view shows up as Break though.
![2016-01-07_00 26 36](https://cloud.githubusercontent.com/assets/16091571/12163700/64bfc00e-b4d5-11e5-9cfa-bd02720f7e37.png)

**Comment by makeo** [comment]
The golem core itself will still work its just the message right?
Anyway fixed next update thanks!

**Comment by malhavok13** [comment]
No, its not working. When i attach the golem to a breakable block, iIcannot give it a pick to use. I tried attaching it to a chest to see if it empties the chest, but its not doing that either. Its like it just showing the wrong interface when clicked.

**Comment by makeo** [comment]
you have to attach the golem to a chest and use the golemancers bell to select the blocks to break.
This feature works and youre not using it correctly...
The only "bug" is the wrong gui message

**Comment by malhavok13** [comment]
Got it, look forward to the next update.

**Comment by makeo** [comment]
Fixed in 1.0.6
