### ISSUE TITLE
Ommiting item array index out of bound in console

### ISSUE THREAD

**Issue by Alaberti** [makeoo/Gadomancy#42]
Haven't confirmed this on a dedicated server, but I noticed the client console showing me this: http://pastebin.com/3L7wR440

Gadomancy 1.0.5, Forge 1566, NEI 1.0.5.118.

**Comment by HellFirePvP** [comment]
This issue is caused by the same problem that was reported in issue #37 - we included an NEI integration for the next update so this won't happen again.

Thanks for the report ;)

**Comment by Alaberti** [comment]
I try lol

**Comment by HellFirePvP** [comment]
By the way, this does not appear server-side and also does not cause any weird bugs. It just spams a bit.. but yea, will be gone on 1.0.6 ;)
