### ISSUE TITLE
Possible ArrayIndexOutOfBoundsException for ItemArcanePackage creating logspam

### ISSUE THREAD

**Issue by midorlo** [makeoo/Gadomancy#45]
Relevant log:

http://pastebin.com/raw/XMat26Vm

Enviroment is win10x64, java8; Modpack is Interminatus (http://www.curse.com/modpacks/minecraft/233642-interminatus)

**Comment by HellFirePvP** [comment]
This is an error with the version 1.0.5 - consider updating to the latest version, we fixxed it.
