### ISSUE TITLE
Crash on server. Tryed both -1 and allocate the enchanting ID myself.

### ISSUE THREAD

**Issue by Kehaan** [makeoo/Gadomancy#46]
Crash on server using newest Gadomancy with GregTech. I have tryed -1 and allocating the ID myself.  Works on client without crash. But on server it instant crashes.

Crashlog here:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/14/16 4:37 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at makeo.gadomancy.common.events.EventHandlerRedirect.onGetEnchantmentLevel(EventHandlerRedirect.java:106)
    at net.minecraft.enchantment.EnchantmentHelper.func_77506_a(EnchantmentHelper.java)
    at gregtech.loaders.oreprocessing.ProcessingArrows.registerOre(ProcessingArrows.java:22)
    at gregtech.api.enums.OrePrefixes.processOre(OrePrefixes.java:700)
    at gregtech.common.GT_Proxy.registerRecipes(GT_Proxy.java:199)
    at gregtech.common.GT_Proxy.activateOreDictHandler(GT_Proxy.java:1897)
    at gregtech.GT_Mod.onPostLoad(GT_Mod.java:451)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1219951568 bytes (1163 MB) / 2077753344 bytes (1981 MB) up to 23049273344 bytes (21981 MB)
    JVM Flags: 7 total; -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Xmx22048M -Xms2048M -XX:MaxMetaspaceSize=512M -XX:+CMSIncrementalPacing -XX:+BindGCTaskThreadsToCPUs
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 109 mods loaded, 109 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
    UCHIJ   Forge{10.13.4.1566} [Minecraft Forge](forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
    UCHIJ   AM2-Preloader{0.0.2} [AMCore](minecraft.jar) 
    UCHIJ   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJ   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJ   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJ   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJ   arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar) 
    UCHIJ   AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft](AgriCraft-1.7.10-1.4.6-hotfix.jar) 
    UCHIJ   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJ   IC2{2.2.810-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.810-experimental.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   Railcraft{9.8.0.0} [Railcraft](Railcraft_1.7.10-9.8.0.0.jar) 
    UCHIJ   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJ   chisel{2.9.4.10} [Chisel](Chisel-2.9.4.10.jar) 
    UCHIJ   ExtrabiomesXL{3.16.4} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.4.jar) 
    UCHIJ   HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar) 
    UCHIJ   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJ   Natura{2.2.0} [Natura](natura-1.7.10-2.2.1a2.jar) 
    UCHIJ   Forestry{4.2.5.53} [Forestry for Minecraft](forestry_1.7.10-4.2.5.53.jar) 
    UCHIJ   koresample{1.7.10-1.3.2} [Kore Sample](KoreSample-1.7.10-1.3.2.jar) 
    UCHIJ   StorageDrawers{1.7.10-1.7.5} [Storage Drawers](StorageDrawers-1.7.10-1.7.5.jar) 
    UCHIJ   dendrology{1.7.10-1.6.4} [Ancient Trees](AncientTrees-1.7.10-1.6.4.jar) 
    UCHIJ   AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJ   ATG{0.10.0} [Alternate Terrain Generation](ATG-1.7.10-0.12.0.jar) 
    UCHIJ   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJ   Automagy{0.27.1} [Automagy](Automagy-1.7.10-0.27.1.jar) 
    UCHIJ   bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
    UCHIJ   BetterAchievements{0.1.0} [Better Achievements](BetterAchievements-1.7.10-0.1.0.jar) 
    UCHIJ   betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) 
    UCHIJ   BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCHIJ   qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.114-universal.jar) 
    UCHIJ   bluepower{0.2.962} [Blue Power](BluePower-1.7.10-0.2.962-universal.jar) 
    UCHIJ   Botania{r1.8-248} [Botania](Botania r1.8-248.jar) 
    UCHIJ   BrandonsCore{1.0.0.10} [Brandon's Core](BrandonsCore-1.0.0.10-bugfix.jar) 
    UCHIJ   chancecubes{1.7.10-1.5.4.54} [Chance Cubes](ChanceCubes-1.7.10-1.5.4.54.jar) 
    UCHIJ   chococraft{4.1.5} [Clienthax's ChocoCraft](ChocoCraft-4.1.5.jar) 
    UCHIJ   DraconicEvolution{1.0.2-snapshot_9} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar) 
    UCHIJ   MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
    UCHIJ   eiramoticons{1.2.83} [EiraMoticons](eiramoticons-mc1.7.10-1.2.83.jar) 
    UCHIJ   endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UCHIJ   etfuturum{1.5.4} [Et Futurum](Et Futurum-1.5.4.jar) 
    UCHIJ   TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7.jar) 
    UCHIJ   ExtraUtilities{1.2.6} [Extra Utilities](extrautilities-1.2.6.jar) 
    UCHIJ   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJ   fastleafdecay{1.4} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.4.jar) 
    UCHIJ   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-513.jar) 
    UCHIJ   ForbiddenMagic{1.7.10-0.573} [Forbidden Magic](Forbidden Magic-1.7.10-0.573.jar) 
    UCHIJ   fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
    UCHIJ   gadomancy{1.0.6.1} [Gadomancy](gadomancy-1.7.10-1.0.6.2.jar) 
    UCHIJ   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.411.jar) 
    UCHIJ   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.411.jar) 
    UCHIJ   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHIE   gregtech{MC1710} [GregTech](gregtech-5.09.19.jar) 
    UCHIJ   galacticgreg{0.7} [Galactic Greg](galacticgreg-0.7.jar) 
    UCHIJ   GardenContainers{1.7.10-1.7.0} [Garden Containers](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJ   GardenCore{1.7.10-1.7.0} [Garden Core](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJ   GardenStuff{1.7.10-1.7.0} [Garden Stuff](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJ   GardenTrees{1.7.10-1.7.0} [Garden Trees](GardenStuff-1.7.10-1.7.0.jar) 
    UCHIJ   gendustry{1.6.4.133} [GenDustry](gendustry-1.6.4.133-mc1.7.10.jar) 
    UCHIJ   GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3.jar) 
    UCHIJ   GTTweaker{1.0.9} [GTTweaker](GTTweaker-1.7.10-1.0.9.jar) 
    UCHIJ   HardcoreDarkness{1.7} [Hardcore Darkness](HardcoreDarkness-MC1.7.10-1.7.jar) 
    UCHIJ   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJ   Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCHIJ   headcrumbs{1.7.2} [Headcrumbs](Headcrumbs-1.7.2.jar) 
    UCHIJ   IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2](IC2NuclearControl-2.3.3a-Exist.jar) 
    UCHIJ   IguanaTweaks{2B} [Iguana Tweaks](IguanaTweaks-1.7.10-2B.jar) 
    UCHIJ   InfernalMobs{1.6.1} [Infernal Mobs](InfernalMobs-1.7.10.jar) 
    UCHIJ   InventoryPets{1.3.8} [Inventory Pets](inventorypets-1.7.10-1.3.8-universal.jar) 
    UCHIJ   inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks](InventoryTweaks-1.59-dev-156.jar) 
    UCHIJ   journeymap{5.1.3} [JourneyMap](journeymap-1.7.10-5.1.3-unlimited.jar) 
    UCHIJ   malisiscore{1.7.10-0.14.0} [MalisisCore](malisiscore-1.7.10-0.14.0.jar) 
    UCHIJ   malisisdoors{1.7.10-1.13.0} [Malisis' Doors](malisisdoors-1.7.10-1.13.0.jar) 
    UCHIJ   MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJ   MobProperties{0.4.1} [Mob Properties](MobProperties-1.7.10-0.4.2.jar) 
    UCHIJ   modtweaker2{0.9.4} [Mod Tweaker 2](ModTweaker2-0.9.5.jar) 
    UCHIJ   NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJ   NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJ   NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJ   NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJ   NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJ   NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJ   NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJ   neiintegration{1.1.0} [NEI Integration](NEIIntegration-MC1.7.10-1.1.0.jar) 
    UCHIJ   Roguelike{1.4.4} [Roguelike Dungeons](roguelike-1.7.10-1.4.4.jar) 
    UCHIJ   RouterReborn{1.2.0.35} [Router Reborn](RouterReborn-1.7.10-1.2.0.35-universal.jar) 
    UCHIJ   SpecialMobs{3.2.1} [Special Mobs](SpecialMobs-1.7.10-3.2.1.jar) 
    UCHIJ   SpiceOfLife{1.3.0} [The Spice of Life](SpiceOfLife-mc1.7.10-1.3.0.jar) 
    UCHIJ   TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    UCHIJ   TextureGeneratorLib{0.2} [TextureGeneratorLib](TextureGeneratorLib-1.7.10_vBeta2.jar) 
    UCHIJ   TGregworks{1.0.7} [Tinkers' Gregworks](TGregworks-1.7.10-1.0.7.jar) 
    UCHIJ   ThaumcraftMobAspects{1.7.x-2B} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.x-2B-snapshot-18.jar) 
    UCHIJ   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHIJ   thaumicenergistics{0.8.10.10} [Thaumic Energistics](thaumicenergistics-0.8.10.10.jar) 
    UCHIJ   ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar) 
    UCHIJ   TiCTooltips{1.2.4} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.4.jar) 
    UCHIJ   TMechworks{0.2.15.106} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.15.106.jar) 
    UCHIJ   wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins](WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
    UCHIJ   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHIJ   WTFCore{1.65} [WhiskyTangoFox's Core](WTFCore-1.7.10_v1.66.jar) 
    UCHIJ   CaveBiomes{1.53} [WhiskyTangoFox's CaveBiomes](WTFCaveBiomes-1.7.10_v1.53.jar) 
    UCHIJ   HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar) 
    UCHIJ   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    UCHIJ   JustAnotherSpawner{0.17.6} [Just Another Spawner](JustAnotherSpawner-0.17.6.jar) 
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    Mantle Environment: Environment healthy.
    TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    List of loaded APIs: 
        \* AgriCraftAPI (1.0) from AgriCraft-1.7.10-1.4.6-hotfix.jar
        \* AppleCoreAPI (1.1.0) from AppleCore-mc1.7.10-1.1.0.jar
        \* appliedenergistics2|API (rv2) from ThaumicTinkerer-2.5-1.7.10-513.jar
        \* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
        \* BetterAchievements|API (0.1.0) from BetterAchievements-1.7.10-0.1.0.jar
        \* bluepowerAPI (1.0) from BluePower-1.7.10-0.2.962-universal.jar
        \* BotaniaAPI (75) from Botania r1.8-248.jar
        \* BuildCraftAPI|core (1.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.8.0.0.jar
        \* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* ChiselAPI (0.1.1) from Chisel-2.9.4.10.jar
        \* ChiselAPI|Carving (0.1.1) from Chisel-2.9.4.10.jar
        \* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.4.10.jar
        \* CoFHAPI (1.7.10R1.0.2) from BrandonsCore-1.0.0.10-bugfix.jar
        \* CoFHAPI|block (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* CoFHAPI|core (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* CoFHAPI|energy (1.7.10R1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
        \* CoFHAPI|fluid (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* CoFHAPI|inventory (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* CoFHAPI|item (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* CoFHAPI|modhelpers (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* CoFHAPI|tileentity (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* CoFHAPI|transport (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.31_beta.jar
        \* CoFHAPI|world (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.35-universal.jar
        \* DraconicEvolution|API (1.2) from Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar
        \* EiraMoticons|API (1.1) from eiramoticons-mc1.7.10-1.2.83.jar
        \* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.5.53.jar
        \* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.5.53.jar
        \* Galacticraft API (1.1) from GalacticraftCore-1.7-3.0.12.411.jar
        \* GardenCoreAPI (1.0.0) from GardenStuff-1.7.10-1.7.0.jar
        \* gendustryAPI (2.3.0) from gendustry-1.6.4.133-mc1.7.10.jar
        \* IC2API (1.0) from industrialcraft-2-2.2.810-experimental.jar
        \* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.3.3a-Exist.jar
        \* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.8.0.0.jar
        \* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.8.0.0.jar
        \* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.7.5.jar
        \* Thaumcraft|API (4.2.2.0) from thaumichorizons-1.7.10-1.1.9.jar
        \* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:ON
    Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Kehaan** [comment]
Also tryed resetting the config, but that does also not work.

**Comment by makeo** [comment]
Thats not an id conflict soo you can't solve using the config..
Gregtech does something weird but I will fix it in a few hours and release a hotfix for that

**Comment by Kehaan** [comment]
Thank you :)

Oh yea, i just tryed different things, to make sure it was not something i did wrong :)

**Comment by makeo** [comment]
No problem :)
We just released a fix for this issue
can you please test our new version in your enviroment?

**Comment by Kehaan** [comment]
Just testet, and confirming it works.

Thank you very much.
