### ISSUE TITLE
Crash, possibly relating to GalactiCraft

### ISSUE THREAD

**Issue by ajthemacboy** [makeoo/Gadomancy#47]
https://gist.github.com/ajthemacboy/9f039846d9bb7b12995b

Edit: wrong crash report, fixed

**Comment by HellFirePvP** [comment]
Have you tried running your pack without Gadomancy? Did it run or not then? Because this crash seems to be unrelated to our mod..

**Comment by ajthemacboy** [comment]
It only crashes with Gadomancy installed.

**Comment by HellFirePvP** [comment]
I'll have a closer look at it.

**Comment by ajthemacboy** [comment]
It only crashes with Gadomancy installed. Make sure you reload the page, I posted the wrong link.

**Comment by HellFirePvP** [comment]
Now that looks more relateable.

**Comment by HellFirePvP** [comment]
In case you haven't noticed yet, we released version 1.0.6.3 that should fix that issue. If it didn't fix it, feel free to reopen the issue again.
