### ISSUE TITLE
Removing Gadomancy causes crashes due to potion effect

### ISSUE THREAD

**Issue by kayila** [makeoo/Gadomancy#52]
It seems like something Gadomancy did with potion effects leaves something funky on the server....

After (temporarilly) removing Gadomancy to try and recover from issue #51 I tried logging back into the server. This resulted in (since I was in the nether and the nether had been regenned) me falling into lava and dieing.

Upon respawning, it looks like the game tried to give me a potion effect, which then crashed the client completely. It also seemed to crash everyone else who was nearby me on the server with very similar crash reports.

Full crash report:
https://gist.github.com/kayila/7020f236d580251407d4

**Comment by Shadows-of-Fire** [comment]
Some mods dynamically generate potions ids. You may have to go through and re-assign all ids. Try PotionIDHelper, it extends the potion array and detects any conflicts.

**Comment by HellFirePvP** [comment]
Good morning - Yea, please check your potion ID's - and if you left the potion ID's from gadomancy in the config at -1 try assigning them manually instead of letting them auto assign. That might fix it..

**Comment by HellFirePvP** [comment]
CLOSED

So what's the overall lession? Don't remove mods if u have blocks of the mod in your world, items of the mod in your inventory, enchantments or potion effects of that mod on you or on your items, AND SO ON. sorry if that might sound a bit harsh
