### ISSUE TITLE
Portal of the voidwalker suggestion: Giving the research "ENTEROUTER"

### ISSUE THREAD

**Issue by kindlich** [makeoo/Gadomancy#56]
Heyho!

I am making a thaumcraft based skyblock pack and wanted to use the gadomancy portal to let people go to the outer lands! Unfortunately, even if you use that portal to go there, you won't get the research called ENTEROUTER, as the gadomancy eldritch DIM has an other ID than the thaumcraft one.

That's why I wanted to ask, if it's possible, to change the thaumcraft research so that you get the research for either entering the outerlands or the gadomancy DIM?

**Comment by HellFirePvP** [comment]
You have to get Ancient Stone and stuff from the real thaumcraft maze before being able to enter Gadomancy's dimension. And if you get the ancient stone - for example on a public server - on a shop or related so you don't need to enter thaumcraft's dimension first, well then...

Hmm mby yea, i'm going to include that..

**Comment by HellFirePvP** [comment]
Added. Will be included.
