### ISSUE TITLE
Golemic Shielding Research bugged

### ISSUE THREAD

**Issue by spannerman79** [makeoo/Gadomancy#57]
Images say it all - no end point/s
![2016-04-05_09 09 26](https://cloud.githubusercontent.com/assets/7542384/14266800/5c1440ea-fb0e-11e5-973c-65ec3028314b.png)
![2016-04-05_09 09 44](https://cloud.githubusercontent.com/assets/7542384/14266810/6e2048b0-fb0e-11e5-9731-3aa686603c97.png)

Right now the only way to get this is `/tc research <user> GADOMANCY.GOLEMRUNICSHIELD`

**Comment by makeo** [comment]
you can complete the research just place aer or potentia next to the auram aspect and it should work but this is not intended

Edit by HellFirePvP: Aer or Praecantatio

**Comment by HellFirePvP** [comment]
Unable to reproduce in any environment/modpack... - If anyone else comes across this: Adding 1 aer or praecantatio to the single auram solves the research node.

CLOSED

**Comment by TwelveBaud** [comment]
Just reproduced this in the Simply Magic 1.1.2 modpack
