### ISSUE TITLE
FakePlayer UUID

### ISSUE THREAD

**Issue by spannerman79** [makeoo/Gadomancy#59]
What is gadomancy's fake player UUID?

**Comment by Barhandar** [comment]
[super(world, new GameProfile(UUID.fromString("d36a4fa5-c70e-4358-8418-9ed683687d0a"), "bla"));](https://github.com/makeoo/Gadomancy/blob/master/src/main/java/makeo/gadomancy/common/entities/player/FakePlayerEntity.java#L22)

Also not a very creative name.

**Comment by spannerman79** [comment]
hm strange, I'm using Fake Player Detector ( https://github.com/KaiKikuchi/FakePlayerDetector ) and it shows up as `[gadomancy:bunchofrandomnumbers]`

**Comment by HellFirePvP** [comment]
Why is it important to you anyway? And that does not belong to the issues section. _Closed_

**Comment by makeo** [comment]
just to inform you if youre still intrested were using multiple fakeplayer UUIDs and not only one
