### ISSUE TITLE
Mirrored jars

### ISSUE THREAD

**Issue by Yacuty** [makeoo/Gadomancy#61]
I just can't find a way to unlink them, i gave up on search, to there is 6 jars linked but i just use 2 so from 8 of essentia i just got 2 and sometimes 3, there is a way to unlink or nah?

**Comment by HellFirePvP** [comment]
"Shift + right click in the air to clear the network." - mod project page - features section.

*Addition: With the jar you want to unlink from the network

**Comment by HellFirePvP** [comment]
Guess that solved the "issue"/question

CLOSED
