### ISSUE TITLE
Ethereal Familiar Research Not Possible

### ISSUE THREAD

**Issue by NRGuy2000** [makeoo/Gadomancy#63]
In the research of the ethereal familiar, the auram is in a place that can't be connected. It is made with Aer and Praecantatio and doesn't make anything else. Is there any other thaumcraft side mods that help with that?
![2016-06-01_21 33 59](https://cloud.githubusercontent.com/assets/19700973/15733180/ad0d0d1a-2840-11e6-9555-93c31b9bf9c6.png)

**Comment by Shadows-of-Fire** [comment]
Well. That's new. Last I checked that research worked just fine.
I can't think of an aspect that combines any of those.

**Comment by HellFirePvP** [comment]
The research grid is generated freshly whenever you create a new research note. Just throw that one away and start over again. Sometimes it's not possible to connect all aspects. That was also discovered during development and is intended.

**Comment by HellFirePvP** [comment]
Closed.
