### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AzzyTheDreemurr** [makeoo/Gadomancy#72]
I'm getting this crash and i have no clue why.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/1/16 9:41 PM
Description: Exception in server tick loop

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    makeo/gadomancy/common/utils/world/ChunkProviderTCOuter.func_73154_d(II)Lnet/minecraft/world/chunk/Chunk; @143: aload_3
  Reason:
    Type long (current frame, locals[3]) is not assignable to reference type
  Current Frame:
    bci: @143
    flags: { }
    locals: { 'makeo/gadomancy/common/utils/world/ChunkProviderTCOuter', integer, integer, long, long_2nd, 'makeo/gadomancy/common/utils/world/fake/FakeWorldTCGeneration$ChunkBuffer', integer }
    stack: { 'net/minecraft/world/World', integer, integer }
  Bytecode:
    0x0000000: 2a2a b400 2bb8 0040 1b85 1c85 1020 7981
    0x0000010: 42b2 0046 b400 4a21 b800 50b6 0054 9906
    0x0000020: a2b2 0046 b400 4a21 b800 50b6 0058 3a05
    0x0000030: 0336 0615 0619 05b4 005b bea2 0040 1905
    0x0000040: b400 5b15 0632 b200 61a6 002c b200 61b2
    0x0000050: 0046 1506 100b 7a10 0f7e 1b07 7880 1506
    0x0000060: 107f 7e15 0610 077a 100f 7e1c 0778 80b2
    0x0000070: 0061 b600 6784 0601 a7ff bbb2 0046 b400
    0x0000080: 4a21 b800 50b6 006b 572a b400 2b1b 1c2d
    0x0000090: b800 6fbb 0071 592a b400 2b19 05b4 005b
    0x00000a0: 1905 b400 741b 1cb7 0077 3a07 1907 b600
    0x00000b0: 7b3a 06b2 007d 0319 0603 b200 7dbe b800
    0x00000c0: 8319 05b4 0087 b900 8d01 003a 0819 08b9
    0x00000d0: 0094 0100 9900 8819 08b9 0098 0100 c000
    0x00000e0: 9a3a 0919 05b4 005b 1909 0632 b600 a032
    0x00000f0: 2ab4 002b 1905 b400 7419 0906 32b6 00a0
    0x0000100: 33b6 00a4 3a0a 190a c600 5119 0ac1 00a6
    0x0000110: 9900 0cbb 00a8 59b7 00a9 3a0a 2ab4 002b
    0x0000120: 190a b600 b119 0719 0903 32b6 00a0 100f
    0x0000130: 7e19 0904 32b6 00a0 1909 0532 b600 a010
    0x0000140: 0f7e 190a b600 b519 0a19 05b4 0074 1909
    0x0000150: 0632 b600 a033 b500 b8a7 ff74 b200 46b4
    0x0000160: 00bc b900 c201 00b9 00c5 0100 3a08 1908
    0x0000170: b900 9401 0099 03b6 1908 b900 9801 00c0
    0x0000180: 00c7 3a09 b200 46b4 00bc 1909 b900 c902
    0x0000190: 00c0 00ab 3a0a 190a b400 cc07 7a1b a0ff
    0x00001a0: d019 0ab4 00cf 077a 1c9f 0006 a7ff c2bb
    0x00001b0: 00d1 5919 0ab4 00cc 100f 7e19 0ab4 00d4
    0x00001c0: 190a b400 cf10 0f7e b700 d73a 0b19 07b4
    0x00001d0: 00da 190b b900 db02 009a 005f b200 dfbb
    0x00001e0: 00e1 59b7 00e2 12e4 b600 e819 0ab4 00cc
    0x00001f0: b600 eb12 edb6 00e8 190a b400 d4b6 00eb
    0x0000200: 12ed b600 e819 0ab4 00cf b600 eb12 efb6
    0x0000210: 00e8 1907 b400 f2b6 00eb 12ed b600 e819
    0x0000220: 07b4 00f5 b600 ebb6 00f9 b600 ffbb 0101
    0x0000230: 5913 0103 b701 05bf 1907 b400 da19 0bb9
    0x0000240: 00c9 0200 c000 ab3a 0c19 0ac1 0107 9900
    0x0000250: 8619 0cc1 0107 9a00 65b2 00df bb00 e159
    0x0000260: b700 e213 0109 b600 e819 0ab4 00cc b600
    0x0000270: eb12 edb6 00e8 190a b400 d4b6 00eb 12ed
    0x0000280: b600 e819 0ab4 00cf b600 eb13 010b b600
    0x0000290: e819 0ab6 010f b601 14b6 00e8 1301 16b6
    0x00002a0: 00e8 190c b601 0fb6 0114 b600 e8b6 00f9
    0x00002b0: b600 ffbb 0101 59b7 0117 bf19 0cc0 0107
    0x00002c0: b601 1b19 0ac0 0107 b601 1bb6 0120 b601
    0x00002d0: 23a7 0250 190a c100 a699 009c 190c c100
    0x00002e0: a69a 0065 b200 dfbb 00e1 59b7 00e2 1301
    0x00002f0: 09b6 00e8 190a b400 ccb6 00eb 12ed b600
    0x0000300: e819 0ab4 00d4 b600 eb12 edb6 00e8 190a
    0x0000310: b400 cfb6 00eb 1301 0bb6 00e8 190a b601
    0x0000320: 0fb6 0114 b600 e813 0116 b600 e819 0cb6
    0x0000330: 010f b601 14b6 00e8 b600 f9b6 00ff bb01
    0x0000340: 0159 b701 17bf bb01 2559 b701 263a 0d19
    0x0000350: 0d13 0128 190a c000 a6b6 012c b601 3019
    0x0000360: 0d13 0132 02b6 0136 190c c000 a619 0db6
    0x0000370: 013a a701 af19 0ac1 013c 9900 8019 0cc1
    0x0000380: 013c 9a00 65b2 00df bb00 e159 b700 e213
    0x0000390: 0109 b600 e819 0ab4 00cc b600 eb12 edb6
    0x00003a0: 00e8 190a b400 d4b6 00eb 12ed b600 e819
    0x00003b0: 0ab4 00cf b600 eb13 010b b600 e819 0ab6
    0x00003c0: 010f b601 14b6 00e8 1301 16b6 00e8 190c
    0x00003d0: b601 0fb6 0114 b600 e8b6 00f9 b600 ffbb
    0x00003e0: 0101 59b7 0117 bf19 0cc0 013c 190a c001
    0x00003f0: 3cb4 0140 b501 40a7 012a 190a c101 4299
    0x0000400: 0093 190c c101 429a 0065 b200 dfbb 00e1
    0x0000410: 59b7 00e2 1301 09b6 00e8 190a b400 ccb6
    0x0000420: 00eb 12ed b600 e819 0ab4 00d4 b600 eb12
    0x0000430: edb6 00e8 190a b400 cfb6 00eb 1301 0bb6
    0x0000440: 00e8 190a b601 0fb6 0114 b600 e813 0116
    0x0000450: b600 e819 0cb6 010f b601 14b6 00e8 b600
    0x0000460: f9b6 00ff bb01 0159 b701 17bf bb01 2559
    0x0000470: b701 263a 0d19 0d13 0128 190a c001 42b6
    0x0000480: 0143 b601 3019 0cc0 0142 190d b601 44a7
    0x0000490: 0092 190a c101 4699 006d 190c c101 469a
    0x00004a0: 0082 b200 dfbb 00e1 59b7 00e2 1301 09b6
    0x00004b0: 00e8 190a b400 ccb6 00eb 12ed b600 e819
    0x00004c0: 0ab4 00d4 b600 eb12 edb6 00e8 190a b400
    0x00004d0: cfb6 00eb 1301 0bb6 00e8 190a b601 0fb6
    0x00004e0: 0114 b600 e813 0116 b600 e819 0cb6 010f
    0x00004f0: b601 14b6 00e8 b600 f9b6 00ff bb01 0159
    0x0000500: b701 17bf bb01 0159 bb00 e159 b700 e213
    0x0000510: 0148 b600 e819 0ab6 014b b600 f9b7 0105
    0x0000520: bf19 08b9 014d 0100 a7fc 46b2 0046 b401
    0x0000530: 50b9 008d 0100 3a09 1909 b900 9401 0099
    0x0000540: 0119 1909 b900 9801 003a 0a19 0ac1 0009
    0x0000550: 9900 6919 0ac0 0009 3a0b 190b b401 538e
    0x0000560: 077a 1ba0 ffd5 190b b401 558e 077a 1c9f
    0x0000570: 0006 a7ff c6bb 0157 592a b400 2b19 0bb4
    0x0000580: 0153 190b b401 5a19 0bb4 0155 190b b401
    0x0000590: 5eb7 0161 3a0c 190c 0eb5 0164 190c 0eb5
    0x00005a0: 0167 190c 0eb5 016a 1907 190c b601 6e19
    0x00005b0: 09b9 014d 0100 a700 9f19 0ac1 000e 9900
    0x00005c0: 7a19 0ac0 000e 3a0b 190b b401 6f8e 077a
    0x00005d0: 1ba0 ff67 190b b401 708e 077a 1c9f 0006
    0x00005e0: a7ff 58bb 0172 592a b400 2bb7 0175 3a0c
    0x00005f0: 190c 190b b401 6f19 0bb4 0176 190b b401
    0x0000600: 70b6 017a 190c 190b b401 7eb4 0181 190b
    0x0000610: b401 7eb4 0184 190b b401 7eb4 0187 190b
    0x0000620: b401 8a8e b601 8e19 0719 0cb6 016e 1909
    0x0000630: b901 4d01 00a7 0020 bb01 0159 bb00 e159
    0x0000640: b700 e213 0190 b600 e819 0ab6 014b b600
    0x0000650: f9b7 0105 bfa7 fee3 0336 0a15 0a10 10a2
    0x0000660: 005e 1032 360b 150b 1040 a200 4d03 360c
    0x0000670: 150c 1010 a200 3d15 0a10 0f7e 0778 150c
    0x0000680: 100f 7e80 1007 7815 0b80 360d 1905 b401
    0x0000690: 9615 0d2e 360e 150e 9e00 1319 07b2 019c
    0x00006a0: 150a 150b 150c 150e b601 a084 0c01 a7ff
    0x00006b0: c284 0b01 a7ff b284 0a01 a7ff a1a7 0058
    0x00006c0: b201 a2be bd00 633a 05b2 01a2 0319 0503
    0x00006d0: b201 a2be b800 83b2 01a4 bebc 083a 06b2
    0x00006e0: 01a4 0319 0603 b201 a4be b800 83bb 0071
    0x00006f0: 592a b400 2b19 0519 061b 1cb7 0077 3a07
    0x0000700: 1907 b600 7b3a 08b2 007d 0319 0803 b200
    0x0000710: 7dbe b800 8319 07b6 01a7 1907 b0  
  Stackmap Table:
    append_frame(@51,Long,Object[#17],Integer)
    same_frame_extended(@117)
    same_frame(@123)
    full_frame(@205,{Object[#2],Integer,Integer,Long,Object[#17],Object[#142],Object[#113],Object[#144]},{})
    append_frame(@284,Object[#154],Object[#171])
    same_frame(@345)
    chop_frame(@348,2)
    same_frame(@366)
    append_frame(@431,Object[#199],Object[#171])
    append_frame(@568,Object[#209])
    append_frame(@699,Object[#171])
    same_frame(@724)
    same_frame_extended(@838)
    same_frame(@885)
    same_frame_extended(@999)
    same_frame(@1018)
    same_frame_extended(@1132)
    same_frame(@1170)
    same_frame_extended(@1284)
    same_frame(@1313)
    full_frame(@1323,{Object[#2],Integer,Integer,Long,Object[#17],Object[#142],Object[#113],Object[#144]},{})
    append_frame(@1336,Object[#144])
    append_frame(@1397,Object[#4],Object[#9])
    chop_frame(@1465,1)
    append_frame(@1507,Object[#14])
    chop_frame(@1592,1)
    append_frame(@1621,Object[#4],Object[#402])
    chop_frame(@1624,3)
    append_frame(@1627,Integer)
    append_frame(@1638,Integer)
    append_frame(@1648,Integer)
    append_frame(@1707,Integer,Integer)
    chop_frame(@1713,2)
    chop_frame(@1719,1)
    chop_frame(@1725,1)
    full_frame(@1728,{Object[#2],Integer,Integer,Long},{})
    full_frame(@1813,{Object[#2],Integer,Integer,Long,Object[#4],Object[#142],Object[#113],Object[#4]},{})

```
at makeo.gadomancy.common.utils.world.WorldProviderTCEldrich.func_76555_c(WorldProviderTCEldrich.java:65)
at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:654)
at net.minecraft.world.World.<init>(World.java:245)
at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Possibly involved mods --
Details:
    Gadomancy: Version: 1.0.7.2. Main class: makeo.gadomancy.common.Gadomancy. Source: gadomancy-1.7.10-1.0.7.2.jar. Url: .
    Gadomancy: Version: 1.0.7.2. Main class: makeo.gadomancy.common.Gadomancy. Source: gadomancy-1.7.10-1.0.7.2.jar. Url: .
    Gadomancy: Version: 1.0.7.2. Main class: makeo.gadomancy.common.Gadomancy. Source: gadomancy-1.7.10-1.0.7.2.jar. Url: .
    Gadomancy: Version: 1.0.7.2. Main class: makeo.gadomancy.common.Gadomancy. Source: gadomancy-1.7.10-1.0.7.2.jar. Url: .
    Gadomancy: Version: 1.0.7.2. Main class: makeo.gadomancy.common.Gadomancy. Source: gadomancy-1.7.10-1.0.7.2.jar. Url: .
    Gadomancy: Version: 1.0.7.2. Main class: makeo.gadomancy.common.Gadomancy. Source: gadomancy-1.7.10-1.0.7.2.jar. Url: .
    Gadomancy: Version: 1.0.7.2. Main class: makeo.gadomancy.common.Gadomancy. Source: gadomancy-1.7.10-1.0.7.2.jar. Url: .

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1989810232 bytes (1897 MB) / 3381133312 bytes (3224 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 103 mods loaded, 103 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA dendrology{1.7.10-1.6.4} [Ancient Trees](AncientTrees-1.7.10-1.6.4.jar) 
    UCHIJAA AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAA aobd{2.9.1} [Another One Bites The Dust](AOBD-2.9.1.jar) 
    UCHIJAA AppleCore{1.3.0} [AppleCore](AppleCore-mc1.7.10-1.3.0.jar) 
    UCHIJAA Automagy{0.28.2} [Automagy](Automagy-1.7.10-0.28.2.jar) 
    UCHIJAA BNBGamingLib{2.3.2} [BNBGamingLib](BNBGamingLib-2.3.2.jar) 
    UCHIJAA Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAA BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCHIJAA Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHIJAA CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAA chisel{2.9.5.11} [Chisel](Chisel-2.9.5.11.jar) 
    UCHIJAA <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAA CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHIJAA CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAA CustomMainMenu{1.9.2} [Custom Main Menu](CustomMainMenu-MC1.7.10-1.9.2.jar) 
    UCHIJAA DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) 
    UCHIJAA DimensionalAnchors{59.0.2} [Dimensional Anchors](dimensional-anchor-59.0.2.jar) 
    UCHIJAA DimensionalControl{1.6.1} [DimensionalControl](DimensionalControl-1.6.1.jar) 
    UCHIJAA lootablebodies{1.3.6} [DrCyano's Lootable Bodies](CyanosLootableBodies-1.7.10-backport_1.3.6.jar) 
    UCHIJAA DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V12e.jar) 
    UCHIJAA <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCHIJAA DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UCHIJAA DynamicLights{1.3.8} [Dynamic Lights](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAA DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAA Enchiridion{1.3} [Enchiridion](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJAA Enchiridion2{2.0.2a} [Enchiridion 2](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJAA endercore{1.7.10-0.2.0.32_beta} [EnderCore](EnderCore-1.7.10-0.2.0.32_beta.jar) 
    UCHIJAA ESM{10.0.148} [Epic Siege Mod](EpicSiegeMod-10.0.148.jar) 
    UCHIJAA essenthaum{1.1.1710.0} [Essential Thaumaturgy](EssentialThaumaturgy-1.1.1710.11EC%284.4.1710.37%29TC%284.2.3.5%29.jar) 
    UCHIJAA essentialcraft{4.6.1710.63} [Essential Craft 3](EssentialCraftv4.6.1710.63.jar) 
    UCHIJAA fastleafdecay{1.4} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.4.jar) 
    UCHIJAA FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHIJAA Steamcraft{0.28.12} [Flaxbeard's Steam Power](Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
    UCHIJAA ForbiddenMagic{1.7.10-0.574} [Forbidden Magic](Forbidden Magic-1.7.10-0.574.jar) 
    UCHIJAA ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAA FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAA ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAA gadomancy{1.0.7.2} [Gadomancy](gadomancy-1.7.10-1.0.7.2.jar) 
    UCHIJAA HardcoreDarkness{1.7} [Hardcore Darkness](HardcoreDarkness-MC1.7.10-1.7.jar) 
    UCHIJAA ImmibisCore{59.1.1} [Immibis Core](immibis-core-59.1.1.jar) 
    UCHIJAA InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) 
    UCHIJAA inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAA IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAA JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAA journeymap{5.1.4} [JourneyMap](journeymap-1.7.10-5.1.4-unlimited.jar) 
    UCHIJAA JustAnotherSpawner{0.17.7} [Just Another Spawner](JustAnotherSpawner-0.17.7.jar) 
    UCHIJAA koresample{1.7.10-1.3.2} [Kore Sample](KoreSample-1.7.10-1.3.2.jar) 
    UCHIJAA llor{1.0.7-mc1.7.10} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.7-mc1.7.10.jar) 
    UCHIJAA MagicCookie{1.0.7.1} [Magic Cookies, something yummy](MagicCookies-1.0.7.1.jar) 
    UCHIJAA mdeco{0.3.5} [Magical Decorations](MagicalDecorations-0.3.5.jar) 
    UCHIJAA MeteorCraft{1.0} [MeteorCraft](MeteorCraft 1.7.10 V12a.jar) 
    UCHIJAA MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJAA mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAA Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAA McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAA modtweaker2{0.9.5} [Mod Tweaker 2](ModTweaker2-0.9.5.jar) 
    UCHIJAA MutantCreatures{1.4.9} [Mutant Creatures](MutantCreatures-1.7.10-1.4.9.jar) 
    UCHIJAA neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHIJAA NaturalAbsorption{1.2.1} [Natural Absorption](NaturalAbsorption-1.7.10-1.2.1.jar) 
    UCHIJAA NodalMechanics{1.7.10R1.0} [NodalMechanics](NodalMechanics-1.7-1.0-7.jar) 
    UCHIJAA NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJAA neresources{0.1.0.ManuallyBuilt} [Not Enough Resources](NotEnoughResources-1.7.10-0.1.0-121.jar) 
    UCHIJAA bt{1.0.2} [NotEnoughThaumcraftTabs](NotEnoughThaumcraftTabs-1.0.2.jar) 
    UCHIJAA ResourceLoader{1.3} [Resource Loader](ResourceLoader-MC1.7.10-1.3.jar) 
    UCHIJAA SilentGems{1.3.13} [Silent's Gems](SilentGems-1.7.10-1.3.13-171.jar) 
    UCHIJAA SimpleAchievements{MC1.7.10-1.1.0-21} [Simple Achievements](SimpleAchievements-MC1.7.10-1.1.0-21.jar) 
    UCHIJAA SquidAPI{1.1.14} [SquidAPI](SquidAPI-1.1.15.jar) 
    UCHIJAA SquidUtils{2.1.3} [SquidUtils](SquidUtils-2.1.4.jar) 
    UCHIJAA StartingInventory{1.7.10.r03} [StartingInventory]([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
    UCHIJAA StorageDrawers{1.7.10-1.9.7} [Storage Drawers](StorageDrawers-1.7.10-1.9.7.jar) 
    UCHIJAA StorageDrawersMisc{1.7.10-1.1.2} [Storage Drawers: Misc Pack](StorageDrawers-Misc-1.7.10-1.1.2.jar) 
    UCHIJAA symcalc{0.14} [Symcalc](symcalc-0.14.jar) 
    UCHIJAA tcinventoryscan{1.0.11} [TC Inventory Scanning](tcinventoryscan-mc1.7.10-1.0.11.jar) 
    UCHIJAA tcnodetracker{1.1.2} [TC Node Tracker](tcnodetracker-1.7.10-1.1.2.jar) 
    UCHIJAA TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    UCHIJAA technom{0.12.5} [Technomancy](Technomancy - 0.12.5 - 1.7.10.jar) 
    UCHIJAA technomCore{0.12.5} [Technomancy Core](minecraft.jar) 
    UCHIJAA Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAA thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHIJAA thaumicbases{1.3.1710.2} [Thaumic Bases](ThaumicBases-1.3.1710.4.jar) 
    UCHIJAA ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-53.jar) 
    UCHIJAA ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar) 
    UCHIJAA thaumicinfusion{4.32} [Thaumic Infusion](ThaumicInfusion-4.32.jar) 
    UCHIJAA ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJAA ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAA TU{1.0} [Thaumic Upholstry](Thaumic_Upholstery-1.2_1.7.10.jar) 
    UCHIJAA TravellersGear{1.16.6} [Traveller's Gear](TravellersGear-1.7.10-1.16.6.jar) 
    UCHIJAA vocation{GRADLE:VERSION-GRADLE:BUILD} [Vocation](Vocation 1.0-1.jar) 
    UCHIJAA wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins](WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
    UCHIJAA Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAA WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCHIJAA wawla{1.3.1} [What Are We Looking At](Wawla-1.0.5.120.jar) 
    UCHIJAA WitchingGadgets{1.1.10} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.10.jar) 
    UCHIJAA WitchingGadgetsCore{1.1.10} [Witching Gadgets Core](minecraft.jar) 
    UCHIJAA bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    CoFHCore: -[1.7.10]3.1.2-325
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by HellFirePvP** [comment]
This is an ASM error i've not seen before, nor do i know which mod it might be related to.

If you're willing to nail down the issue, try removing mod by mod until the error disappears. Other than that, not sure how we could be of any assistance.

In any case i'm gonna close this issue; if you find the source of this problem, feel free to reopen and inform us.
