### ISSUE TITLE
Crash related to Issue #51

### ISSUE THREAD

**Issue by chaos234** [makeoo/Gadomancy#73]
Hey,

I got the same crash like reported in #51 so it must be Gadomancy since it is the only mod which tries to cast smth. to EntityLivingBase in the End.

The Nether self runs smooth and there are no errors also in SP are no errors, client crashes only on MP.
I also changed those IDs in the gadomancy.cfg but without any luck.

It would be glad if there is a known fix for that. Since it is a privat MP (modified Infinity Evolved 2.6 pack) I must send you all related files.

Launcher-Log, incl. Crash report: https://paste.ee/p/vTrgS

**Comment by chaos234** [comment]
I found out, that it seem to be have to do with ChocoCraft (which implements Chocobos). After I have removed it, the error disappeared.

I don't know if a fix is possible but if so it would be glad to fix it.

**Comment by HellFirePvP** [comment]
From what we've gathered so far, this is an entityType id mismatch between server and client - which doesn't happen in SP obviously. Apparently it starts to appear if you add Gadomancy to an existing world/pack.

As we are unable to exactly locate where this originates from, we can't do much about it. If we're doing another 1.7.10 Gadomancy version, there might be a fix for it if we come across this.

**Comment by chaos234** [comment]
Thanks for the rplay @HellFirePvP .

Is there no way with "some special magic from java" to get a list from the client and server side entityType IDs?
