### ISSUE TITLE
wrongly attributed issue (nothing important here)

### ISSUE THREAD

**Issue by shadoxxhd** [makeoo/Gadomancy#81]
after upgrading from 1.0.7.2 to 1.0.7.3 I had a crash:
crash log: http://pastebin.com/guUF9b1K

only significant correlation to the youshallnotstack mod; seeming relation to gadomancy was most probably coincidental

**Comment by HellFirePvP** [comment]
Pretty sure this is another mod's problem.
Namely

> at com.InfinityRaider.YouShallNotStack.YouShallNotStack.postInit(YouShallNotStack.java:32)

Remove that mod and try again~

**Comment by shadoxxhd** [comment]
seemed related to gadomancy update, but I'll do some tests

**Comment by shadoxxhd** [comment]
interestingly, the client works when using the exact same mod list + configs...

**Comment by shadoxxhd** [comment]
downgrading gadomancy did not fox the issue. after removing youshallnotstack both gadomancy versions worked fine. correlation might still exist (ie. update might have modified some stack in a way ysns doesn't like) but is not nearly significant enough to warrant keeping this issue open.
